//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Event> Events { get; set; }
        public DbSet<Field> Fields { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Requirement> Requirements { get; set; }
        public DbSet<Respons> Responses { get; set; }
        public DbSet<Submission> Submissions { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<TextQuestion> TextQuestions { get; set; }
        public DbSet<VideoQuestion> VideoQuestions { get; set; }
        public DbSet<WorkflowButton> WorkflowButtons { get; set; }
        public DbSet<WorkflowQuestion> WorkflowQuestions { get; set; }
        public DbSet<Workflow> Workflows { get; set; }
    }
}
