//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int FieldID { get; set; }
        public int RequiredID { get; set; }
        public int EventID { get; set; }
        public string Value { get; set; }
    }
}
