//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowButton
    {
        public int WorkflowButtonID { get; set; }
        public int WorkflowQuestionID { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public int NextWorkflowQuestionID { get; set; }
        public int Display { get; set; }
    }
}
